apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dof-exam/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-host
  name: nginx-host
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dof-exam/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-host
    spec:
      containers:
      - image: nginx-host
        name: nginx-host
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /site
          name: nginx-host-claim0
      restartPolicy: Always
      volumes:
      - name: nginx-host-claim0
        persistentVolumeClaim:
          claimName: nginx-host-claim0
status: {}
