apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php-host
    spec:
      containers:
        - image: d3nislav/php-host:%IMAGE-PLACEHOLDER%
          name: php-host
          ports:
            - containerPort: 9000
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  type: NodePort
  ports:
    - name: "30913"
      port: 30913
      targetPort: 30913
  selector:
    io.kompose.service: php-host
